models = [
    "openai/gpt-4o-2024-08-06",
    "openai/gpt-4o-2024-05-13",
    "openai/gpt-4o-mini-2024-07-18",
    "openai/gpt-4-0314",
    "openai/gpt-4-1106-preview",
    "openai/gpt-4-turbo",  # Newest Turbo
    "openai/chatgpt-4o-latest",
    "openai/o1-mini",
    "openai/o1-preview",
    "meta-llama/llama-3.1-8b-instruct",
    "meta-llama/llama-3.1-70b-instruct",
    "meta-llama/llama-3.1-405b-instruct",
    "meta-llama/llama-3.1-405b-instruct:bf16",
    "meta-llama/llama-3.2-3b-instruct",
    "meta-llama/llama-3.2-1b-instruct",
    "meta-llama/llama-3.2-90b-vision-instruct",
    "meta-llama/llama-3.2-11b-vision-instruct",
    "anthropic/claude-3-5-haiku-20241022",
    "anthropic/claude-3.5-sonnet",  # New Sonnet
    "anthropic/claude-3.5-sonnet-20240620",  # Old Sonnet
    "anthropic/claude-3-sonnet",
    "anthropic/claude-3-opus",
    "anthropic/claude-3-haiku",
    "google/gemini-flash-1.5-8b",
    "google/gemini-flash-1.5",
    "google/gemini-pro-1.5",
    "google/gemma-2-27b-it",
    "google/gemma-2-9b-it",
    "x-ai/grok-beta",
    "mistralai/mixtral-8x22b-instruct",
    "mistralai/mistral-large-latest",
    "mistralai/mistral-7b-instruct-v0.3",
]

model_prices = [
    {'model': 'openai/gpt-4o-2024-08-06', 'input_price': 2.5, 'output_price': 10},   
    {'model': 'openai/gpt-4o-2024-05-13', 'input_price': 5, 'output_price': 15},
    {'model': 'openai/gpt-4o-mini-2024-07-18', 'input_price': 0.15, 'output_price': 0.6},
    {'model': 'openai/gpt-4-0314', 'input_price': 30, 'output_price': 60},
    {'model': 'openai/gpt-4-1106-preview', 'input_price': 10, 'output_price': 30},
    {'model': 'openai/gpt-4-turbo', 'input_price': 10, 'output_price': 30},
    {'model': 'openai/o1-mini', 'input_price': 3, 'output_price': 12},
    {'model': 'openai/o1-preview', 'input_price': 15, 'output_price': 60},
    {'model': 'meta-llama/llama-3.1-8b-instruct', 'input_price': 0.05, 'output_price': 0.05},
    {'model': 'meta-llama/llama-3.1-70b-instruct', 'input_price': 0.34, 'output_price': 0.39},
    {'model': 'meta-llama/llama-3.1-405b-instruct', 'input_price': 2.75, 'output_price': 2.75},
    {'model': 'meta-llama/llama-3.1-405b-instruct:bf16', 'input_price': 3, 'output_price': 3},
    {'model': 'meta-llama/llama-3.2-3b-instruct', 'input_price': 0.03, 'output_price': 0.05},
    {'model': 'meta-llama/llama-3.2-1b-instruct', 'input_price': 0.01, 'output_price': 0.02},
    {'model': 'meta-llama/llama-3.2-90b-vision-instruct', 'input_price': 0.9, 'output_price': 0.9},
    {'model': 'meta-llama/llama-3.2-11b-vision-instruct', 'input_price': 0.055, 'output_price': 0.055},
    {'model': 'anthropic/claude-3-5-haiku-20241022', 'input_price': 1, 'output_price': 5},
    {'model': 'anthropic/claude-3.5-sonnet', 'input_price': 3, 'output_price': 15},
    {'model': 'anthropic/claude-3.5-sonnet-20240620', 'input_price': 3, 'output_price': 15},
    {'model': 'anthropic/claude-3-sonnet', 'input_price': 3, 'output_price': 15},
    {'model': 'anthropic/claude-3-opus', 'input_price': 15, 'output_price': 75},
    {'model': 'anthropic/claude-3-haiku', 'input_price': 0.25, 'output_price': 1.25},
    {'model': 'google/gemini-flash-1.5-8b', 'input_price': 0.0375, 'output_price': 0.15},
    {'model': 'google/gemini-flash-1.5-pro', 'input_price': 0.075, 'output_price': 0.3},
    {'model': 'google/gemini-pro-1.5', 'input_price': 1.25, 'output_price': 5},
    {'model': 'google/gemma-2-27b-it', 'input_price': 0.27, 'output_price': 0.27},
    {'model': 'google/gemma-2-9b-it', 'input_price': 0.06, 'output_price': 0.06},
    {'model': 'x-ai/grok-beta', 'input_price': 5, 'output_price': 15},
    {'model': 'mistralai/mixtral-8x22b-instruct', 'input_price': 0.9, 'output_price': 0.9},
    {'model': 'mistralai/mistral-large-latest', 'input_price': 2, 'output_price': 6},
    {'model': 'mistralai/mistral-7b-instruct-v0.3', 'input_price': 0.055, 'output_price': 0.055},
]

model_subset = [
    "openai/gpt-4o-mini-2024-07-18",
    "meta-llama/llama-3.1-70b-instruct",
    "google/gemini-flash-1.5-8b",
    "anthropic/claude-3.5-sonnet",  # New Sonnet
    "gpt-4-turbo"
]
