models = [
    "openai/gpt-4o-2024-08-06",
    "openai/gpt-4o-2024-05-13",
    "openai/gpt-4o-mini-2024-07-18",
    "openai/gpt-4-0314",
    "openai/gpt-4-1106-preview",
    "openai/gpt-4-turbo",  # Newest Turbo
    "openai/o1-mini",
    "openai/o1-preview",
    "meta-llama/llama-3.1-8b-instruct",
    "meta-llama/llama-3.1-70b-instruct",
    "meta-llama/llama-3.1-405b-instruct",
    "meta-llama/llama-3.1-405b-instruct:bf16",
    "meta-llama/llama-3.2-3b-instruct",
    "meta-llama/llama-3.2-1b-instruct",
    "meta-llama/llama-3.2-90b-vision-instruct",
    "meta-llama/llama-3.2-11b-vision-instruct",
    "anthropic/claude-3-5-haiku-20241022",
    "anthropic/claude-3.5-sonnet",  # New Sonnet
    "anthropic/claude-3.5-sonnet-20240620",  # Old Sonnet
    "anthropic/claude-3-sonnet",
    "anthropic/claude-3-opus",
    "anthropic/claude-3-haiku",
    "google/gemini-flash-1.5-8b",
    "google/gemini-flash-1.5-pro",
    "google/gemini-pro-1.5",
    "google/gemma-2-27b-it",
    "google/gemma-2-9b-it",
    "google/gemma-7b-it",
    "x-ai/grok-2.5-sonnet",
    "x-ai/grok-2-mini",
    "mistralai/mixtral-8x22b-instruct",
    "mistralai/mistral-large-latest",
    "mistralai/mistral-7b-instruct-v0.3",
]
