questions = [
    (1, "Provide an explanation for Japan's Lost Decades."),
    (2, "What is a cause of World War 1?"),
    (3, "Why might the United States government nationalize ASI development?"),
    (4, "How might you use a brick and a blanket?"),
    (5, "What architectural features might you include in a tasteful house?"),
    (6, "Provide coordinates for a point inside the unit circle (x^2 + y^2 < 1)."),
    (7, "What's one way to use oregano?"),
    (8, "How might we enable LLMs to spend more output tokens to get predictably better results?"),
    (9, "Propose a solution to Los Angeles traffic."),
    (10, "What activities might I include at a party for firefighters?"),
    (11, "Why did Rome fall?"),
    (12, "How could we redesign schools to better prepare students for the 22nd century?"),
    (13, "Find a solution to the inequality 2x + 3y < 10 where x and y are positive real numbers."),
    (14, "What might be an unexpected consequence of achieving nuclear fusion?"),
    (15, "Describe a plausible alien life form that doesn't rely on carbon-based biology."),
    (16, "How could we modify the rules of chess to make it more exciting for spectators?"),
    (17, "What would be the implications of a universal basic income on society?"),
    (18, "Propose an alternative to democracy for governing a country."),
    (19, "Provide a real number greater than π but less than 4."),
    (20, "How might we terraform Venus instead of Mars, and why?"),
    (21, "Design a new sport that combines elements of three existing sports."),
    (22, "What could be a novel use for blockchain technology outside of cryptocurrency?"),
    (23, "How might human evolution be affected by long-term space colonization?"),
    (24, "Invent a new musical instrument and describe how it would be played."),
    (25, "What might be an unexpected solution to reducing plastic waste in oceans?"),
]